kuma:
  controlPlane:
    mode: "zone"

    tls:
      apiServer:
        # (action): please prepare the content of this secret before installing Kuma
        # it contains the keys "tls.crt" and "tls.key", and the content items should be in "PEM" format
        # more details on preparing certificates: https://kuma.io/docs/latest/production/secure-deployment/certificates/
        secretName: kuma-apiserver-tls

    apiServer:
      corsAllowedDomains:
        # change these values you want to access the control plane API server or Mesh GUI from a custom domain
        - https://localhost:5682
        # if you want to access the API server using the HTTP port, add the following line
        # - http://localhost:5681

    envVars:
      # if you want to access the API server using the HTTP port, change the following switch to "true"
      KUMA_API_SERVER_HTTP_ENABLED: "false"

    # please tune the resource allocation according to your actual mesh size and traffic load after Kuma is installed.
    # try to make the resource limits identical to requests to make components are assigned as a QoS class of Guaranteed
    # more details on sizing the CP: https://kuma.io/docs/latest/introduction/kuma-requirements/#sizing-your-control-plane
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 1024Mi

    replicas: 2
    autoscaling:
      enabled: true

      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 50


    podDisruptionBudget:
      enabled: true

  cni:
    # -- Install Kuma with CNI instead of proxy init container
    enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
