kuma:
  controlPlane:
    mode: "zone"
    # (action): please specify a name for the zone
    zone:

    tls:
      apiServer:
        # (action): please prepare the content of this secret before installing Kuma
        # it contains the keys "tls.crt" and "tls.key", and the content items should be in "PEM" format
        # more details on preparing certificates: https://kuma.io/docs/latest/production/secure-deployment/certificates/
        secretName: kuma-apiserver-tls
        kdsZoneClient:
          # (action): please prepare the content of this secret before installing Kuma
          # the certificate can be extracted from the trusted global CP server
          # it should contain the key "ca.crt", and the content certificate should be in "PEM" format
          # more details on certificates verifying: https://kuma.io/docs/latest/production/secure-deployment/certificates/#control-plane-to-control-plane-multizone
          secretName: kuma-kds-global-ca
          skipVerify: false

    apiServer:
      corsAllowedDomains:
        # change these values you want to access the control plane API server or Mesh GUI from a custom domain
        - https://localhost:5682
        # if you want to access the API server using the HTTP port, add the following line
        # - http://localhost:5681

    # (action): please specify the address of the global CP
    # e.g. grpcs://my-global-cp.my-hostname.com:5685
    kdsGlobalAddress: ""

    envVars:
      # if you want to access the API server using the HTTP port, change the following switch to "true"
      KUMA_API_SERVER_HTTP_ENABLED: "false"

    # please tune the resource allocation according to your actual mesh size and traffic load after Kuma is installed.
    # try to make the resource limits identical to requests to make components are assigned as a QoS class of Guaranteed
    # more detail on sizing the CP: https://kuma.io/docs/latest/introduction/kuma-requirements/#sizing-your-control-plane
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 1024Mi

    replicas: 2
    autoscaling:
      enabled: true

      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 50


    podDisruptionBudget:
      enabled: true

  cni:
    # -- Install Kuma with CNI instead of proxy init container
    enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi

  ingress:
    # -- If true, it deploys Ingress for cross cluster communication
    enabled: false
    # please tune the resource allocation according to your actual mesh size and traffic load after Kuma is installed.
    # try to make the resource limits identical to requests to make components are assigned as a QoS class of Guaranteed
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 1024Mi

    replicas: 2
    autoscaling:
      enabled: true
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 50

    podDisruptionBudget:
      enabled: true
