name: backport
run-name: ${{ format( 'backport #{0} to branches {1}', inputs.PR, ( inputs.branches && format( 'branches {0}', inputs.branches) || 'active branches' )) }}
on:
  workflow_dispatch:
    inputs:
      PR:
        description: "number of the PR to be backported"
        type: string
        default: ""
        required: true
      branches:
        description: "target branches for backport (leave empty to target all active branches that applies)"
        type: string
        default: ""
        required: false
jobs:
  maybe-backport:
    uses: ./.github/workflows/_backport_wfc.yaml
    permissions:
      contents: read
      pull-requests: write
    with:
        pr_number: ${{ inputs.PR }}
        target_branches: ${{ inputs.branches }}
